## Filter DataFrame

In [1]:
 import pandas as pd

In [2]:
groceries = pd.read_pickle('Data/groceries_with_new_columns.pkl')
groceries.head()

,Product_ID,Product_ID_Num,Category,Subcategory,Item,Organic,Price_Dollars,Inventory,Percent Inventory,Low Inventory,Last_Updated,Last_Updated_Time,Next_Scheduled_Shipment,Shipment_Date_DOW
0,P100010,100010,Produce,Fruit,Apple,False,1.50,349,7.2,,2023-06-12 15:35:00,15:35:00,2023-06-15,Thursday
1,P100011,100011,Produce,Fruit,Banana,False,0.40,500,10.3,,2023-06-12 18:30:00,18:30:00,2023-06-15,Thursday
2,P100012,100012,Produce,Fruit,Grapes,False,4.00,200,4.1,,2023-06-12 17:22:00,17:22:00,2023-06-15,Thursday
3,P100013,100013,Produce,Fruit,Grapefruit,False,0.99,50,1.0,,2023-06-12 16:29:00,16:29:00,2023-06-15,Thursday
4,P100014,100014,Produce,Fruit,Organic Strawberries,True,3.99,148,3.0,,2023-06-12 18:10:00,18:10:00,2023-06-15,Thursday

In [3]:
groceries.loc[groceries['Low Inventory'] == 'Low Inventory']

,Product_ID,Product_ID_Num,Category,Subcategory,Item,Organic,Price_Dollars,Inventory,Percent Inventory,Low Inventory,Last_Updated,Last_Updated_Time,Next_Scheduled_Shipment,Shipment_Date_DOW
15,P100025,100025,Produce,Dairy,Milk (Soy),False,4.49,32,0.7,Low Inventory,2023-06-13 08:37:00,08:37:00,2023-06-17,Saturday
17,P100027,100027,Pantry,Snacks,Apple Sauce - organic,True,1.50,27,0.6,Low Inventory,2023-06-10 12:02:00,12:02:00,2023-06-24,Saturday
20,P100030,100030,Pantry,Snacks,Raisins,False,2.99,5,0.1,Low Inventory,2023-06-10 12:38:00,12:38:00,2023-06-24,Saturday

In [6]:
groceries.loc[groceries['Low Inventory'] == 'Low Inventory', ['Price_Dollars', 'Inventory']]

    Price_Dollars  Inventory
15           4.49         32
17           1.50         27
20           2.99          5

In [7]:
groceries[groceries.Subcategory == ' Snacks'] # Returns nothing but we do have products with the Snacks subcategory.

Empty DataFrame
Columns: [Product_ID, Product_ID_Num, Category, Subcategory, Item, Organic, Price_Dollars, Inventory, Percent Inventory, Low Inventory, Last_Updated, Last_Updated_Time, Next_Scheduled_Shipment, Shipment_Date_DOW]
Index: []

In [8]:
groceries.Subcategory[0] # Space before subcategory.

' Fruit'

In [9]:
groceries[groceries.Subcategory == ' Snacks'] # Add space

,Product_ID,Product_ID_Num,Category,Subcategory,Item,Organic,Price_Dollars,Inventory,Percent Inventory,Low Inventory,Last_Updated,Last_Updated_Time,Next_Scheduled_Shipment,Shipment_Date_DOW
17,P100027,100027,Pantry,Snacks,Apple Sauce - organic,True,1.50,27,0.6,Low Inventory,2023-06-10 12:02:00,12:02:00,2023-06-24,Saturday
18,P100028,100028,Pantry,Snacks,Chips,False,2.50,365,7.5,,2023-06-10 12:12:00,12:12:00,2023-06-24,Saturday
19,P100029,100029,Pantry,Snacks,Cookies (Oatmeal),False,5.39,340,7.0,,2023-06-10 12:24:00,12:24:00,2023-06-24,Saturday
20,P100030,100030,Pantry,Snacks,Raisins,False,2.99,5,0.1,Low Inventory,2023-06-10 12:38:00,12:38:00,2023-06-24,Saturday

In [10]:
# Clean spaces in subcategory
groceries.Subcategory = groceries.Subcategory.str.strip()

In [11]:
groceries.Subcategory[0]

'Fruit'

In [12]:
groceries[groceries.Subcategory == 'Snacks']

,Product_ID,Product_ID_Num,Category,Subcategory,Item,Organic,Price_Dollars,Inventory,Percent Inventory,Low Inventory,Last_Updated,Last_Updated_Time,Next_Scheduled_Shipment,Shipment_Date_DOW
17,P100027,100027,Pantry,Snacks,Apple Sauce - organic,True,1.50,27,0.6,Low Inventory,2023-06-10 12:02:00,12:02:00,2023-06-24,Saturday
18,P100028,100028,Pantry,Snacks,Chips,False,2.50,365,7.5,,2023-06-10 12:12:00,12:12:00,2023-06-24,Saturday
19,P100029,100029,Pantry,Snacks,Cookies (Oatmeal),False,5.39,340,7.0,,2023-06-10 12:24:00,12:24:00,2023-06-24,Saturday
20,P100030,100030,Pantry,Snacks,Raisins,False,2.99,5,0.1,Low Inventory,2023-06-10 12:38:00,12:38:00,2023-06-24,Saturday

In [13]:
mask = (groceries['Low Inventory'] == 'Low Inventory') & (groceries.Subcategory == 'Snacks')

In [14]:
groceries[mask] # Filter rows

,Product_ID,Product_ID_Num,Category,Subcategory,Item,Organic,Price_Dollars,Inventory,Percent Inventory,Low Inventory,Last_Updated,Last_Updated_Time,Next_Scheduled_Shipment,Shipment_Date_DOW
17,P100027,100027,Pantry,Snacks,Apple Sauce - organic,True,1.50,27,0.6,Low Inventory,2023-06-10 12:02:00,12:02:00,2023-06-24,Saturday
20,P100030,100030,Pantry,Snacks,Raisins,False,2.99,5,0.1,Low Inventory,2023-06-10 12:38:00,12:38:00,2023-06-24,Saturday

In [15]:
groceries.loc[mask, ['Subcategory', 'Item', 'Inventory']] # Filter on columns as well

   Subcategory                   Item  Inventory
17      Snacks  Apple Sauce - organic         27
20      Snacks                Raisins          5

## Sort dataframe

In [16]:
groceries.sort_values('Price_Dollars') # Lowest to highest

,Product_ID,Product_ID_Num,Category,Subcategory,Item,Organic,Price_Dollars,Inventory,Percent Inventory,Low Inventory,Last_Updated,Last_Updated_Time,Next_Scheduled_Shipment,Shipment_Date_DOW
1,P100011,100011,Produce,Fruit,Banana,False,0.40,500,10.3,,2023-06-12 18:30:00,18:30:00,2023-06-15,Thursday
9,P100019,100019,Produce,Vegetable,Cucumber,False,0.99,230,4.7,,2023-06-12 17:47:00,17:47:00,2023-06-15,Thursday
3,P100013,100013,Produce,Fruit,Grapefruit,False,0.99,50,1.0,,2023-06-12 16:29:00,16:29:00,2023-06-15,Thursday
16,P100026,100026,Produce,Dairy,Yogurt,False,1.00,432,8.9,,2023-06-13 08:41:00,08:41:00,2023-06-17,Saturday
17,P100027,100027,Pantry,Snacks,Apple Sauce - organic,True,1.50,27,0.6,Low Inventory,2023-06-10 12:02:00,12:02:00,2023-06-24,Saturday
0,P100010,100010,Produce,Fruit,Apple,False,1.50,349,7.2,,2023-06-12 15:35:00,15:35:00,2023-06-15,Thursday
6,P100016,100016,Produce,Vegetable,Cabbage,False,1.78,78,1.6,,2023-06-12 19:25:00,19:25:00,2023-06-15,Thursday
8,P100018,100018,Produce,Vegetable,Celery,False,1.99,50,1.0,,2023-06-12 16:42:00,16:42:00,2023-06-15,Thursday
7,P100017,100017,Produce,Vegetable,Carrots,False,2.00,200,4.1,,2023-06-12 18:05:00,18:05:00,2023-06-15,Thursday
18,P100028,100028,Pantry,Snacks,Chips,False,2.50,365,7.5,,2023-06-10 12:12:00,12:12:00,2023-06-24,Saturday
20,P100030,100030,Pantry,Snacks,Raisins,False,2.99,5,0.1,Low Inventory,2023-06-10 12:38:00,12:38:00,2023-06-24,Saturday
14,P100024,100024,Produce,Dairy,Eggs,False,3.29,234,4.8,,2023-06-13 08:54:00,08:54:00,2023-06-17,Saturday
13,P100023,100023,Produce,Dairy,Butter,False,3.50,400,8.2,,2023-06-13 08:35:00,08:35:00,2023-06-17,Saturday
4,P100014,100014,Produce,Fruit,Organic Strawberries,True,3.99,148,3.0,,2023-06-12 18:10:00,18:10:00,2023-06-15,Thursday
2,P100012,100012,Produce,Fruit,Grapes,False,4.00,200,4.1,,2023-06-12 17:22:00,17:22:00,2023-06-15,Thursday
15,P100025,100025,Produce,Dairy,Milk (Soy),False,4.49,32,0.7,Low Inventory,2023-06-13 08:37:00,08:37:00,2023-06-17,Saturday
22,P100032,100032,Frozen,Frozen Snacks,Spinach Dip,False,4.96,76,1.6,,2023-05-28 22:05:00,22:05:00,2023-06-28,Wednesday
19,P100029,100029,Pantry,Snacks,Cookies (Oatmeal),False,5.39,340,7.0,,2023-06-10 12:24:00,12:24:00,2023-06-24,Saturday
5,P100015,100015,Produce,Fruit,Watermelon,False,5.99,99,2.0,,2023-06-12 19:15:00,19:15:00,2023-06-15,Thursday
21,P100031,100031,Frozen,Frozen Snacks,Chicken Nuggets,False,6.99,85,1.8,,2023-05-28 22:02:00,22:02:00,2023-06-28,Wednesday
24,P100034,100034,Frozen,Frozen Fruit,Frozen Pineapple,False,7.96,178,3.7,,2023-05-28 22:11:00,22:11:00,2023-06-28,Wednesday
12,P100022,100022,Produce,Meat,Turkey,False,7.99,188,3.9,,2023-06-13 07:32:00,07:32:00,2023-06-17,Saturday
10,P100020,100020,Produce,Meat,Beef,False,8.99,145,3.0,,2023-06-13 07:00:00,07:00:00,2023-06-17,Saturday
11,P100021,100021,Produce,Meat,Chicken (Organic),True,10.49,284,5.8,,2023-06-13 07:20:00,07:20:00,2023-06-17,Saturday
23,P100033,100033,Frozen,Frozen Fruit,Frozen Blueberries,False,10.99,162,3.3,,2023-05-28 22:14:00,22:14:00,2023-06-28,Wednesday

In [18]:
groceries.sort_values('Price_Dollars', ascending=False) # highest to lowest

,Product_ID,Product_ID_Num,Category,Subcategory,Item,Organic,Price_Dollars,Inventory,Percent Inventory,Low Inventory,Last_Updated,Last_Updated_Time,Next_Scheduled_Shipment,Shipment_Date_DOW
23,P100033,100033,Frozen,Frozen Fruit,Frozen Blueberries,False,10.99,162,3.3,,2023-05-28 22:14:00,22:14:00,2023-06-28,Wednesday
11,P100021,100021,Produce,Meat,Chicken (Organic),True,10.49,284,5.8,,2023-06-13 07:20:00,07:20:00,2023-06-17,Saturday
10,P100020,100020,Produce,Meat,Beef,False,8.99,145,3.0,,2023-06-13 07:00:00,07:00:00,2023-06-17,Saturday
12,P100022,100022,Produce,Meat,Turkey,False,7.99,188,3.9,,2023-06-13 07:32:00,07:32:00,2023-06-17,Saturday
24,P100034,100034,Frozen,Frozen Fruit,Frozen Pineapple,False,7.96,178,3.7,,2023-05-28 22:11:00,22:11:00,2023-06-28,Wednesday
21,P100031,100031,Frozen,Frozen Snacks,Chicken Nuggets,False,6.99,85,1.8,,2023-05-28 22:02:00,22:02:00,2023-06-28,Wednesday
5,P100015,100015,Produce,Fruit,Watermelon,False,5.99,99,2.0,,2023-06-12 19:15:00,19:15:00,2023-06-15,Thursday
19,P100029,100029,Pantry,Snacks,Cookies (Oatmeal),False,5.39,340,7.0,,2023-06-10 12:24:00,12:24:00,2023-06-24,Saturday
22,P100032,100032,Frozen,Frozen Snacks,Spinach Dip,False,4.96,76,1.6,,2023-05-28 22:05:00,22:05:00,2023-06-28,Wednesday
15,P100025,100025,Produce,Dairy,Milk (Soy),False,4.49,32,0.7,Low Inventory,2023-06-13 08:37:00,08:37:00,2023-06-17,Saturday
2,P100012,100012,Produce,Fruit,Grapes,False,4.00,200,4.1,,2023-06-12 17:22:00,17:22:00,2023-06-15,Thursday
4,P100014,100014,Produce,Fruit,Organic Strawberries,True,3.99,148,3.0,,2023-06-12 18:10:00,18:10:00,2023-06-15,Thursday
13,P100023,100023,Produce,Dairy,Butter,False,3.50,400,8.2,,2023-06-13 08:35:00,08:35:00,2023-06-17,Saturday
14,P100024,100024,Produce,Dairy,Eggs,False,3.29,234,4.8,,2023-06-13 08:54:00,08:54:00,2023-06-17,Saturday
20,P100030,100030,Pantry,Snacks,Raisins,False,2.99,5,0.1,Low Inventory,2023-06-10 12:38:00,12:38:00,2023-06-24,Saturday
18,P100028,100028,Pantry,Snacks,Chips,False,2.50,365,7.5,,2023-06-10 12:12:00,12:12:00,2023-06-24,Saturday
7,P100017,100017,Produce,Vegetable,Carrots,False,2.00,200,4.1,,2023-06-12 18:05:00,18:05:00,2023-06-15,Thursday
8,P100018,100018,Produce,Vegetable,Celery,False,1.99,50,1.0,,2023-06-12 16:42:00,16:42:00,2023-06-15,Thursday
6,P100016,100016,Produce,Vegetable,Cabbage,False,1.78,78,1.6,,2023-06-12 19:25:00,19:25:00,2023-06-15,Thursday
17,P100027,100027,Pantry,Snacks,Apple Sauce - organic,True,1.50,27,0.6,Low Inventory,2023-06-10 12:02:00,12:02:00,2023-06-24,Saturday
0,P100010,100010,Produce,Fruit,Apple,False,1.50,349,7.2,,2023-06-12 15:35:00,15:35:00,2023-06-15,Thursday
16,P100026,100026,Produce,Dairy,Yogurt,False,1.00,432,8.9,,2023-06-13 08:41:00,08:41:00,2023-06-17,Saturday
3,P100013,100013,Produce,Fruit,Grapefruit,False,0.99,50,1.0,,2023-06-12 16:29:00,16:29:00,2023-06-15,Thursday
9,P100019,100019,Produce,Vegetable,Cucumber,False,0.99,230,4.7,,2023-06-12 17:47:00,17:47:00,2023-06-15,Thursday
1,P100011,100011,Produce,Fruit,Banana,False,0.40,500,10.3,,2023-06-12 18:30:00,18:30:00,2023-06-15,Thursday

In [19]:
groceries.sort_values(['Subcategory', 'Price_Dollars'])

,Product_ID,Product_ID_Num,Category,Subcategory,Item,Organic,Price_Dollars,Inventory,Percent Inventory,Low Inventory,Last_Updated,Last_Updated_Time,Next_Scheduled_Shipment,Shipment_Date_DOW
16,P100026,100026,Produce,Dairy,Yogurt,False,1.00,432,8.9,,2023-06-13 08:41:00,08:41:00,2023-06-17,Saturday
14,P100024,100024,Produce,Dairy,Eggs,False,3.29,234,4.8,,2023-06-13 08:54:00,08:54:00,2023-06-17,Saturday
13,P100023,100023,Produce,Dairy,Butter,False,3.50,400,8.2,,2023-06-13 08:35:00,08:35:00,2023-06-17,Saturday
15,P100025,100025,Produce,Dairy,Milk (Soy),False,4.49,32,0.7,Low Inventory,2023-06-13 08:37:00,08:37:00,2023-06-17,Saturday
24,P100034,100034,Frozen,Frozen Fruit,Frozen Pineapple,False,7.96,178,3.7,,2023-05-28 22:11:00,22:11:00,2023-06-28,Wednesday
23,P100033,100033,Frozen,Frozen Fruit,Frozen Blueberries,False,10.99,162,3.3,,2023-05-28 22:14:00,22:14:00,2023-06-28,Wednesday
22,P100032,100032,Frozen,Frozen Snacks,Spinach Dip,False,4.96,76,1.6,,2023-05-28 22:05:00,22:05:00,2023-06-28,Wednesday
21,P100031,100031,Frozen,Frozen Snacks,Chicken Nuggets,False,6.99,85,1.8,,2023-05-28 22:02:00,22:02:00,2023-06-28,Wednesday
1,P100011,100011,Produce,Fruit,Banana,False,0.40,500,10.3,,2023-06-12 18:30:00,18:30:00,2023-06-15,Thursday
3,P100013,100013,Produce,Fruit,Grapefruit,False,0.99,50,1.0,,2023-06-12 16:29:00,16:29:00,2023-06-15,Thursday
0,P100010,100010,Produce,Fruit,Apple,False,1.50,349,7.2,,2023-06-12 15:35:00,15:35:00,2023-06-15,Thursday
4,P100014,100014,Produce,Fruit,Organic Strawberries,True,3.99,148,3.0,,2023-06-12 18:10:00,18:10:00,2023-06-15,Thursday
2,P100012,100012,Produce,Fruit,Grapes,False,4.00,200,4.1,,2023-06-12 17:22:00,17:22:00,2023-06-15,Thursday
5,P100015,100015,Produce,Fruit,Watermelon,False,5.99,99,2.0,,2023-06-12 19:15:00,19:15:00,2023-06-15,Thursday
12,P100022,100022,Produce,Meat,Turkey,False,7.99,188,3.9,,2023-06-13 07:32:00,07:32:00,2023-06-17,Saturday
10,P100020,100020,Produce,Meat,Beef,False,8.99,145,3.0,,2023-06-13 07:00:00,07:00:00,2023-06-17,Saturday
11,P100021,100021,Produce,Meat,Chicken (Organic),True,10.49,284,5.8,,2023-06-13 07:20:00,07:20:00,2023-06-17,Saturday
17,P100027,100027,Pantry,Snacks,Apple Sauce - organic,True,1.50,27,0.6,Low Inventory,2023-06-10 12:02:00,12:02:00,2023-06-24,Saturday
18,P100028,100028,Pantry,Snacks,Chips,False,2.50,365,7.5,,2023-06-10 12:12:00,12:12:00,2023-06-24,Saturday
20,P100030,100030,Pantry,Snacks,Raisins,False,2.99,5,0.1,Low Inventory,2023-06-10 12:38:00,12:38:00,2023-06-24,Saturday
19,P100029,100029,Pantry,Snacks,Cookies (Oatmeal),False,5.39,340,7.0,,2023-06-10 12:24:00,12:24:00,2023-06-24,Saturday
9,P100019,100019,Produce,Vegetable,Cucumber,False,0.99,230,4.7,,2023-06-12 17:47:00,17:47:00,2023-06-15,Thursday
6,P100016,100016,Produce,Vegetable,Cabbage,False,1.78,78,1.6,,2023-06-12 19:25:00,19:25:00,2023-06-15,Thursday
8,P100018,100018,Produce,Vegetable,Celery,False,1.99,50,1.0,,2023-06-12 16:42:00,16:42:00,2023-06-15,Thursday
7,P100017,100017,Produce,Vegetable,Carrots,False,2.00,200,4.1,,2023-06-12 18:05:00,18:05:00,2023-06-15,Thursday

In [21]:
groceries[groceries['Low Inventory'] == 'Low Inventory'].sort_values('Price_Dollars')

,Product_ID,Product_ID_Num,Category,Subcategory,Item,Organic,Price_Dollars,Inventory,Percent Inventory,Low Inventory,Last_Updated,Last_Updated_Time,Next_Scheduled_Shipment,Shipment_Date_DOW
17,P100027,100027,Pantry,Snacks,Apple Sauce - organic,True,1.50,27,0.6,Low Inventory,2023-06-10 12:02:00,12:02:00,2023-06-24,Saturday
20,P100030,100030,Pantry,Snacks,Raisins,False,2.99,5,0.1,Low Inventory,2023-06-10 12:38:00,12:38:00,2023-06-24,Saturday
15,P100025,100025,Produce,Dairy,Milk (Soy),False,4.49,32,0.7,Low Inventory,2023-06-13 08:37:00,08:37:00,2023-06-17,Saturday

## Grouping

In [25]:
groceries.head(3)

,Product_ID,Product_ID_Num,Category,Subcategory,Item,Organic,Price_Dollars,Inventory,Percent Inventory,Low Inventory,Last_Updated,Last_Updated_Time,Next_Scheduled_Shipment,Shipment_Date_DOW
0,P100010,100010,Produce,Fruit,Apple,False,1.5,349,7.2,,2023-06-12 15:35:00,15:35:00,2023-06-15,Thursday
1,P100011,100011,Produce,Fruit,Banana,False,0.4,500,10.3,,2023-06-12 18:30:00,18:30:00,2023-06-15,Thursday
2,P100012,100012,Produce,Fruit,Grapes,False,4.0,200,4.1,,2023-06-12 17:22:00,17:22:00,2023-06-15,Thursday

In [26]:
groceries.groupby('Category')['Inventory'].sum()

Category
Frozen      501
Pantry      737
Produce    3619
Name: Inventory, dtype: int64

In [27]:
groceries.groupby('Category')['Inventory'].count()

Category
Frozen      4
Pantry      4
Produce    17
Name: Inventory, dtype: int64

In [29]:
groceries.groupby(['Category', 'Subcategory'])['Inventory'].count().reset_index()

  Category    Subcategory  Inventory
0   Frozen   Frozen Fruit          2
1   Frozen  Frozen Snacks          2
2   Pantry         Snacks          4
3  Produce          Dairy          4
4  Produce          Fruit          6
5  Produce           Meat          3
6  Produce      Vegetable          4

In [33]:
(groceries.groupby(['Category', 'Subcategory'])['Inventory']
          .agg(['sum', 'count'])
          .reset_index())

  Category    Subcategory   sum  count
0   Frozen   Frozen Fruit   340      2
1   Frozen  Frozen Snacks   161      2
2   Pantry         Snacks   737      4
3  Produce          Dairy  1098      4
4  Produce          Fruit  1346      6
5  Produce           Meat   617      3
6  Produce      Vegetable   558      4

In [34]:
groceries.head(2)

,Product_ID,Product_ID_Num,Category,Subcategory,Item,Organic,Price_Dollars,Inventory,Percent Inventory,Low Inventory,Last_Updated,Last_Updated_Time,Next_Scheduled_Shipment,Shipment_Date_DOW
0,P100010,100010,Produce,Fruit,Apple,False,1.5,349,7.2,,2023-06-12 15:35:00,15:35:00,2023-06-15,Thursday
1,P100011,100011,Produce,Fruit,Banana,False,0.4,500,10.3,,2023-06-12 18:30:00,18:30:00,2023-06-15,Thursday

In [43]:
# Find most expensive item in each category

In [38]:
# INCORRECT. Applies max to item and price.
groceries.groupby('Category')[['Item', 'Price_Dollars']].max()

                 Item  Price_Dollars
Category
Frozen    Spinach Dip          10.99
Pantry        Raisins           5.39
Produce        Yogurt          10.49

In [42]:
# Correct
(groceries[['Category', 'Item', 'Price_Dollars']]
 .sort_values('Price_Dollars', ascending=False)
 .groupby('Category')
 .head(1)
)

   Category                Item  Price_Dollars
23   Frozen  Frozen Blueberries          10.99
11  Produce   Chicken (Organic)          10.49
19   Pantry   Cookies (Oatmeal)           5.39